apiVersion: v1
kind: Pod
metadata:
  name: umair-pod-1
spec:
  containers:
  - name: writer
    image: busybox
    command: ["sh", "-c", "echo 'Umair_Pod_1 : Add 2+2' > /data/result.txt"]
    volumeMounts:
    - name: vol
      mountPath: /data
    resources:
      limits:
        memory: "128Mi"
        cpu: "250m"
      requests:
        memory: "64Mi"
        cpu: "100m"
  restartPolicy: Never
  volumes:
  - name: vol
    persistentVolumeClaim:
      claimName: mashraf1-pvc
