apiVersion: v1
kind: Pod
metadata:
  name: umair-writer-pod
spec:
  containers:
  - name: umair-pod-container
    image: centos:centos7
    command: ["sh", "-c","echo 'Im a new pod created by umair' > /data/umair2.txt && sleep 60"]
    volumeMounts:
    - name: vol
      mountPath: /data


    resources:
      limits:
        memory: "1Gi"
        cpu: "2"
      requests:
        memory: "512Mi"
        cpu: "1"
  restartPolicy: Never
  volumes:
  - name: vol
    persistentVolumeClaim:
      claimName: mashraf1-pvc
